### ISSUE TITLE
Can't even get the library installed because of documentation

### ISSUE THREAD

**Issue by andymboyle** [dreamsolution/django-auth-policy#11]
These docs need some work, and you don't even have any basics for what the bits in the main Django settings file are supposed to be (even for defaults). Currently getting this error after following what documentation there is:

`NoReverseMatch: Reverse for 'password_change' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []`

Any thoughts or additions to the docs that could help folks start up and use this would be great, because I would much rather use this than django-password-policies. Thanks!

**Comment by rudolphfroger** [comment]
You are completely right, the lack of documentation is hindering this project severely. Please have a look at the "testsite" which is used in all the tests but also has a minimal Django Auth Policy setup. You are more than welcome to help with setting up the documentation.
